# Generated by Django 5.0.2 on 2024-12-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicapp', '0001_initial'),
        ('turfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookturf',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfapp.slot'),
        ),
        migrations.AddField(
            model_name='bookturf',
            name='turf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfapp.turf'),
        ),
    ]
